# Generated by Django 5.1.5 on 2025-02-01 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_id', models.PositiveIntegerField()),
                ('first_name', models.CharField(max_length=65)),
                ('last_name', models.CharField(max_length=65)),
                ('email', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('gpa', models.FloatField(validators=[django.core.validators.MaxValueValidator(4.0)])),
            ],
        ),
    ]
